trigger:
  branches:
    include:
      - main
      - test
      - prod

pool:
  name: wsl-agent-pool

variables:
  TF_VERSION: '1.5.7'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update && sudo apt-get install -y unzip
      curl -sL https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -o terraform.zip
      unzip terraform.zip
      sudo mv terraform /usr/local/bin/
  displayName: 'Install Terraform'

- checkout: self

- task: AzureCLI@2
  inputs:
    azureSubscription: 'TerraformSP'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd terraform
      terraform init
      terraform apply -var-file="main.tfvars" -auto-approve
  displayName: 'Terraform Init & Apply'
