trigger:
  branches:
    include:
      - main
      - test
      - prod

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: '1.5.7'

steps:
- task: UseTerraform@0
  inputs:
    terraformVersion: $(TF_VERSION)

- checkout: self

- task: AzureCLI@2
  inputs:
    azureSubscription: 'REPLACE_WITH_SERVICE_CONNECTION_NAME'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd terraform
      terraform init
      terraform apply -var-file="main.tfvars" -auto-approve
    displayName: 'Terraform Init & Apply'