name: Deploy Infrastructure

on:
  push:
    branches:
      - main
      - test
      - prod

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -var-file="${{ github.ref_name }}.tfvars" -auto-approve
        working-directory: ./terraform